apiVersion: argoproj.io/v1alpha1               
kind: Rollout
metadata:
  name: myhelmapp
  namespace: helmtest
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myhelmapp
  workloadRef:                                 
    apiVersion: apps/v1
    kind: Deployment
    name: myhelmapp
    scaleDown: onsuccess
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 60s}
